import Head from 'next/head'
import styles from '../styles/home.module.scss'
import { withIronSessionSsr } from 'iron-session/next'
import { ironOptions } from '../lib/config'
import React from 'react'
import { Logo } from '../components/svg/logo'

export const getServerSideProps = withIronSessionSsr(async ({ req }) => {
  const { user } = req.session
  return {
    props: { isLoggedIn: !!user },
  }
}, ironOptions)

const Home: React.FC<{ isLoggedIn: boolean }> = ({ isLoggedIn }) => {
  console.log('isLoggedIn in index', isLoggedIn)
  return (
    <>
      <Head>
        <title>Quapp - Sharing is Caring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>

      <main>
        <section
          className={`bg-gradient-to-br from-violetRed-600 via-violetRed-600 to-violetRed-900`}
        >
          <Logo className="w-full h-[256px]" />
          <h1 className={styles.title}>Die App die Nachbarn verbindet.</h1>
        </section>

        <h1>Die App die Nachbarn verbindet</h1>
        <p>
          Sharing is caring - nach dieser Devise sollten unserer Meinung nach,
          jede Nachbarschaften leben! <strong>Quapp</strong> ermöglicht es dir
          ganz einfach Kontakt zu deiner Nachbarschaft aufzubauen und sich
          gegenseitig zu unterstützen. Biete einfach Hilfe, Werkzeuge oder
          ähnliches in deinen Spaces an oder nutze die Angebote von anderen.
          Gemeinsam sind wir stärker!
        </p>
      </main>

      <footer className={styles.footer}></footer>
    </>
  )
}
export default Home
