import Head from 'next/head'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1 className="text-3xl font-bold underline">
          Hello world, Quartiervereins App mit Tailwind CSS!
        </h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
